### ISSUE TITLE
Comments Impossible to collect

### ISSUE THREAD

**Issue by MBerriche** [medialab/minet#104]
https://www.facebook.com/IPSNaturelle/posts/1175066705875628 

https://www.facebook.com/ludovic.marechal.731/videos/1922686801278544/ 

https://www.facebook.com/permalink.php?story_fbid=919621161551250&id=100005101249468

https://www.facebook.com/watch/?v=992820997487978 

https://www.facebook.com/IPSNaturelle/posts/842936479088654 

https://www.facebook.com/IPSNaturelle/posts/1336108013104829 

https://www.facebook.com/stopmensongesofficiel/posts/1349479791773219 

https://www.facebook.com/IPSNaturelle/posts/1171647102884255 

https://www.facebook.com/ReporterreQuotidienDeLecologie/posts/1509632052418138

https://www.facebook.com/IPSNaturelle/posts/844636245585344

https://www.facebook.com/IPSNaturelle/posts/849584368423865

https://www.facebook.com/stopmensongesofficiel/posts/1056366764417858 

https://www.facebook.com/EnnasriNabil/posts/891236660992854 

https://www.facebook.com/554178414627483/posts/1362570667121583 

https://www.facebook.com/Citizens.Action.Network/posts/467574709982113 

https://www.facebook.com/stopmensongesofficiel/posts/1279071155480750 

https://www.facebook.com/IPSNaturelle/posts/846918138690488 

https://www.facebook.com/554178414627483/posts/1567889329923048 

https://www.facebook.com/cequevouscachentlesmedias/posts/1188187031274557 

https://www.facebook.com/IPSNaturelle/posts/849574731758162

**Comment by MBerriche** [comment]
Les coms de ces 3 urls me serait particulièrement utile : https://www.facebook.com/20minutes/posts/10154146135738311
https://www.facebook.com/PrJoyeux/posts/702807829912557 
https://www.facebook.com/PrJoyeux/posts/590379937822014

**Comment by MBerriche** [comment]
url : https://www.facebook.com/lemonde.fr/posts/10155775351437590

erro message : 
user_label = user_link.get_text().strip()
AttributeError: 'NoneType' object has no attribute 'get_text'
Scraping comments: 0 comments [00:01, ? comments/s]

**Comment by Yomguithereal** [comment]
All those posts can now be scraped for comments :). Be sure to upgrade minet before attempting to do so (https://github.com/medialab/minet#upgrading)
