### ISSUE TITLE
Run my command in Python and not bash

### ISSUE THREAD

**Issue by heloisethero** [medialab/minet#121]
Great work on minet :) If it is possible, I would like to run the following command with Python and not bash : "minet ct summary normalized_url ./clean_data/clean_fake_url.csv --token $token_crowdtangle --posts ./clean_data/fake_posts.csv --sort-by total_interactions --start-date 2019-01-01"

**Comment by Yomguithereal** [comment]
This is now possible through [this](https://github.com/medialab/minet/blob/master/docs/lib.md#crowdtangleclient).
