### ISSUE TITLE
minet fb posts-stat seems to be broken?

### ISSUE THREAD

**Issue by heloisethero** [medialab/minet#181]
I have tried the minet fb posts-stat on different example Facebook URLs with this command:
```
minet fb post-stats url fb_url.csv
```

The last two URLs return `not-facebook-post`, which is normal, but the first five URLs are valid Facebook posts, and they return either `extraction-failed` or `private-or-unavailable`.

The CSV file containing the URLs can be found [here](https://github.com/medialab/cours-facebook/blob/main/input/fb_url.csv).

**Comment by Yomguithereal** [comment]
Bon j'ai corrigé l'heuristique d'extraction. Cela dit, cette méthode reste de toute façon assez peu efficace dans la mesure où soit je m'authentifie mais je me fait kick encore plus vite et je risque un ban de compte ou je ne m'authentifie pas et ya plein de pages auquelles je n'ai pas accès. La peste ou le choléra quoi :). En plus c'est lent quoi qu'il arrive (2 posts par minute). Donc bon c'est "corrigé", je clos :)
