### ISSUE TITLE
minet fb comments adapted to other formats than Facebook posts?

### ISSUE THREAD

**Issue by heloisethero** [medialab/minet#183]
`minet fb comments` gives a `Given url (line n) is not a Facebook post url: the_given_url` error if used on a Facebook video (https://www.facebook.com/108824017345866/videos/311658803718223) or photo (https://www.facebook.com/260769680665568/photos/a.305266056215930/524959150913285).

1/ Would it be possible to return not an error but a warning? This way the command could keep running if one URL among many others in a CSV file is not a Facebook post.

2/ Would it be possible to scrap also comments for these formats, as users can also comment videos and photos?

**Comment by Yomguithereal** [comment]
It should be interesting to see if https://www.facebook.com/santeplusmag/photos/a.309641465765319/4406607732735318 returns the same comments as https://www.facebook.com/santeplusmag/posts/4406608072735284 (it seems not, for more fun).

**Comment by Yomguithereal** [comment]
They are basically the same pool of comments but funnily enough one url returns some more comments than the other...
