### ISSUE TITLE
Twitter scraper: (un)handle blurred searches

### ISSUE THREAD

**Issue by boogheta** [medialab/minet#191]
Twitter occasionnally detects (or suspects) spelling errors in its search inputs and by default returns results combining the actual search query and the corrected one. For instance here: https://twitter.com/search?q=justin%20beiber&src=typed_query (note the src=typed_query added by Twitter, but even without the src argument, it does the same : https://twitter.com/search?q=justin%20beiber )
When clicking on the link to search only for the actual desired query, the url switches by adding a different src argument `&src=spelling_expansion_revert_click` : https://twitter.com/search?q=justin%20beiber&src=spelling_expansion_revert_click
So maybe we should always use this argument when scraping?

**Comment by Yomguithereal** [comment]
That's already the case it seems https://github.com/medialab/minet/blob/master/minet/twitter/api_scraper.py#L51 :)

**Comment by boogheta** [comment]
GG
