### ISSUE TITLE
Time out error for minet ct

### ISSUE THREAD

**Issue by heloisethero** [medialab/minet#192]
When I run a data collection with `minet ct` for a few hours, I often get this error that stops the data collection:
```
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.crowdtangle.com', port=443): Read timed out. (read timeout=300)
```

**Comment by Yomguithereal** [comment]
Which `ct` commands are we talking about? `search`, `posts` I guess? The thing is I am veeeeeery generous with my timeout here (I give them 5 loooooong minutes to answer). But I guess I should implement some retry mecanism here. This can be fast to add but I need to know if this could save the day or not. My guess is that when this happen they may require some hours on their end to fix the issue and I don't know if my retrying can take this into account.

**Comment by heloisethero** [comment]
I don't know if their problem takes hours to be fixed because I have never seen the error on the fly and rer
