### ISSUE TITLE
Add command to collect tweets from user (including retweets) from the API

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/minet#208]

**Comment by Yomguithereal** [comment]
C'est bon @boogheta, @bmaz. Je cracherais pas sur une review de la méthode (notamment concernant le `max_id` etc. parce que je l'ai jamais fait) et sur un test de l'un de vous deux pour me dire si tout est réglo.

**Comment by boogheta** [comment]
Alors déjà quelques remarques sur l'api:
- le help est un peu bizarre : la ligne descriptive est sur deux lignes alors que toutes les lignes suivantes font plus de 80 cars
- il y a un "the" en trop dans la doc de l'option --ids
- j'aurai plutot mis --include-retweets comme l'option par défaut vu que c'est celle de twitter (et que le max de 3200 en tient forcément compte) du coup ptet la transformer en un --ignore-retweets plutot?
- je trouve bizarre de devoir donner le --total pour avoir la loadbar, le csv à charger contenant des metas d'users, il sera jamais surréaliste, compter ses lignes dans minet si total est pas donné me semblerait pas fou, mais bon
- j'imagine que .minetrc marche aussi à la place des clés d'api mais c pas explicitement dit par la doc, y a une raison?
- fournir quelque part la liste des colonnes donnables à -s ?

**Comment by boogheta** [comment]
Sinon l'expérience user est cool, la loadbar est utile mais améliorable je pense : le users= est pas très parlant, si je comprends bien il dit combien sont finis, ça pourrait être pas mal qu'il mette dans ce cas fini/total plutot, voire qu'il indique l'id/handle du compte en cours de traitement.

Par contre il y a un souci avec les tweets collectés dont le texte et les liens ne sont pas complets : il manque je pense l'option extended_tweets=True aux requetes

**Comment by boogheta** [comment]
Et sinon oui l'approche utilisant min(tweet_ids) - 1 pour max_id aux requetes suivantes est la bonne

**Comment by boogheta** [comment]
dernier point : JPC nous demande régulièrement sur ce type de collectes de les rafraichir, du coup avoir un argument en plus permettant de donner un nom de colonne dans lequel se trouverait l'id du dernier tweet collecté par user serait utile pour permettre de recollecter qu'à partir de ceux là (avec l'argument d'api since_id en plus)

**Comment by boogheta** [comment]
et one more question : que se passe-t-il pour les users inexistants/supprimés/protected ? normalement l'api renvoie des 404 dans ces cas là, a minima avoir un log informant que ces comptes ont échoué me semble important

**Comment by boogheta** [comment]
Nickel maintenant.
J'ouvre des issues pour les deux side quests restantes moins prio
