### ISSUE TITLE
weird numbers printed after the progress bar for `minet mc search`

### ISSUE THREAD

**Issue by heloisethero** [medialab/minet#228]
When I run a minet mc search, the numbers printed are a little weird:
```
Searching stories:   6%|████▋                                                                         | 499/8340 [00:02<2:38:41,  1.21s/ stories]

Searching stories:  63%|█████████████████████████████████████████████████                             | 5249/8340 [00:29<00:23, 131.52 stories/s]

```
The number for stories/s goes from around 1 stories/s to around 100-200 stories/s while the progress bar moves. I would have expected this number to be more or less stable, and not increasing through time. But maybe it is normal?

Also the first prints say `s/ stories`, while the later prints say `stories/s`. Maybe it is a typo?

**Comment by Yomguithereal** [comment]
Unfortunately this is related to the way tqdm computes its estimates and those are not very good when the output is especially jittery (at it is the case with mediacloud). I am not sure to know how to improve this. The plural part is also out of my hands and is a known ~bug~ or lack of option on tqdm's side :(
