### ISSUE TITLE
tw scrape fails on some queries due to Over capacity error

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/minet#229]
minet tw scrape tweets '#5gcovid' > tweets.csv

<class 'minet.twitter.exceptions.TwitterPublicAPIInvalidResponseError'>

{'errors': [{'message': 'Over capacity', 'code': 130}]} 503

**Comment by Yomguithereal** [comment]
This also happens when scrolling the website: https://twitter.com/search?q=%235gcovid&src=typed_query&f=live

I should wait until tomorrow and try again to see if it is temporary.

@bmaz @boogheta did you already see this?

**Comment by bmaz** [comment]
No, never seen this

**Comment by boogheta** [comment]
haven't seen thi either, and can't reproduce it on the website even after scrolling a bit far in the past

**Comment by Yomguithereal** [comment]
You did not scroll enough :) Or can you try to run the command on your end and tell me if you can go beyond ~200 tweets?

**Comment by boogheta** [comment]
I have the same issue with the minet command (exactly 200 lines actually), but not when scrolling: I did go way beyond the last tweet minet gets back.
Actually it looks to me like the last one collected is the first one with the disclaimer "! Voir les faits sur le COVID-19" (this one: https://twitter.com/5g_oxygen/status/1356519872390287360 )

**Comment by Yomguithereal** [comment]
I personally get the message when scrolling, even though it comes probably after 200 results indeed. I will try throttling more respectfully to see if this changes anything but my first tests seems to point to the same hard limit. If it does nothing more I think I will add a custom exception and break as soon as we hit this particular wall instead of waiting to retry for nothing.

**Comment by boogheta** [comment]
could it be linked to the fact that I'm testing in the browser while logged in?

**Comment by Yomguithereal** [comment]
No, I also tested whille being logged in

**Comment by boogheta** [comment]
Ha yes got it this time, with two different last tweets on Jan 30th while in private browsing, and Jan 31st while logged in

**Comment by Yomguithereal** [comment]
Yes the last tweet sometimes jitter between ~10 tweets. This is also the case when using minet cli.
