### ISSUE TITLE
Error in installation of standalone CLI tool  on Raspberry Pi OS (Debian)

### ISSUE THREAD

**Issue by mxagat** [medialab/minet#294]
I tried to install Minet on a Raspberry pi zero WH with Raspberry Pi OS  5.10.17. Something goes wrong when trying to install : 
> $ curl -sSL https://raw.githubusercontent.com/medialab/minet/master/scripts/install.sh | bash
>This install script will ask you for your password so it can move/copy
> things to '/usr/local/bin'. If you are not comfortable with this you can
> read the install script here:
> https://github.com/medialab/minet/blob/master/scripts/install.sh
> Installing minet for ubuntu 10 (or similar)...
> Downloading ubuntu_16 binaries for 0.52.3 release...
> Installing...
> Installed:
> bash: line 104: /usr/local/bin/minet: cannot execute binary file: Exec format error
  
  When I try to launch it, the same error comes again :
> minet 
> bash: /usr/local/bin/minet: cannot execute binary file: Exec format error

**Comment by mxagat** [comment]
Update : same issue on a Raspberry Pi 4 with Ubuntu 21.04.  It seems to be a hardware architecture issue.

**Comment by Yomguithereal** [comment]
Unfortunately I don't have the means to support a standalone installation of minet on Raspberry architecture. But a `pip` installation of minet worked on your Raspberry yesterday so we'll say it is good enough  ¯\_(ツ)_/¯
