### ISSUE TITLE
 [minet twitter scrape] add start-date and end-date 

### ISSUE THREAD

**Issue by shadenshabayek** [medialab/minet#298]
Would it be possible please to add among the optional arguments: start-date and end-date?

**Comment by Yomguithereal** [comment]
Hello @shadenshabayek. You can use the `until` and `since` Twitter search operators for this in your query. Like this for instance:

```
test until:2017-02-02 since:2017-01-01
```

See an exemple [here](https://twitter.com/search?q=test%20until%3A2017-02-02%20since%3A2017-01-01&src=typed_query&f=live).

**Comment by Yomguithereal** [comment]
I guess it could be nice to add an example in the CLI help for this though.

**Comment by shadenshabayek** [comment]
perfect thank you!
