### ISSUE TITLE
minet twitter user-tweets --total should take a total number of accounts rather of tweets

### ISSUE THREAD

**Issue by boogheta** [medialab/minet#312]

**Comment by Yomguithereal** [comment]
I must change the progress bar to reflect that and update on users, not tweets. This makes complete sense since the max number of tweets we can retrieve is 3200 anyway.

**Comment by boogheta** [comment]
from my experience it can sometimes be slighly more such as 3250, but since it only serves for rendering the progressbar and that in some cases users will have less tweets than that, I guess approximating with 3200 makes sense
