### ISSUE TITLE
Results of TikTok exploration

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/minet#353]
Trouver les vidéos d'un compte : https://www.tiktok.com/@ayanakamura

On peut chercher :
    - des tags : https://www.tiktok.com/tag/ClimateAction
    - des sons: https://www.tiktok.com/music/TKN-6831569851157317633?lang=en
    - des discover: https://www.tiktok.com/discover/Anime-Fun?lang=en

Si on est loggé : 
    - des vidéos: https://www.tiktok.com/search/video?q=shawarma&t=333863951
    - des comptes: https://www.tiktok.com/search/video?q=shawarma&t=1635339771985
    

On n'a pas accès aux commentaires sans être loggé

Il est possible de scraper mais 1. il faut être authentifié (à part pour dérouler des hashtags), et 2. il faut crafter des requêtes complexes qui exigent un cookie et probablement un émulateur de navigateur pour lancer la recherche.

Procédure manuelle :

1) se logger
2) aller sur une recherche https://www.tiktok.com/search/video?q=climat
3) ouvrir la console : collecter le cookie et l'url de collecte par l'api du type l https://m.tiktok.com/api/search/item/full/
4) scripter les appels de cette url en faisant variant l'offset  (exemple sci-dessous par 12 mais count 20 donc à vérifier)
=> The winner:
    
seq 1 50 |
  while read i; do
    j=$((i*12));
    curl https://m.tiktok.com/api/search/item/full/\?aid\=1988\&app_language\=en\&app_name\=tiktok_web\&browser_language\=en-US\&browser_name\=Mozilla\&browser_online\=true\&browser_platform\=Linux%20x86_64\&browser_version\=5.0%20%28X11%29\&channel\=tiktok_web\&cookie_enabled\=true\&count\=20\&device_id\=7023723730656462342\&device_platform\=web_pc\&focus_state\=true\&from_page\=search\&history_len\=5\&is_fullscreen\=false\&is_page_visible\=true\&keyword\=climat\&offset\=$i\&os\=linux\&priority_region\=\&referer\=\&region\=FR\&root_referer\=https%3A%2F%2Fwww.google.com%2F\&screen_height\=864\&screen_width\=1536\&tz_name\=Europe%2FParis\&verifyFp\=verify_b8c7d480af0e1a55c18e70a05331f565\&msToken\=\&X-Bogus\=DFSzsIVOY7vANSl1Su96AdRUGG0Z\&_signature\=_02B4Z6wo00001rDKnzwAAIDBXs6jgpM.7GKwy5uAAM1Y7c -H 'Cookie: ttwid=1%7CXvTJ9ZY2ZMldqdHq4hBXg6DG0pe-zrdF0tQwA_f8TSM%7C1635340310%7Cf33e1fac57dd255b5540ff1e90d6ccd5960edf11813a80bd7d6fab966f32c17a; tt_csrf_token=bTYbWyTMAhC4rVXJnWppXJsB; R6kq3TV7=AD2Gv8F8AQAA9J_blJ0XVf3_ae1uPoYOZBozIdtdXtrzyad1PR9SEnv1Ijnu|1|0|501fd26da0c40961e80b6c00a1a853509ff02b5c; cookie-consent={%22ga%22:false%2C%22af%22:false%2C%22fbp%22:false%2C%22lip%22:false%2C%22version%22:%22v2%22}; passport_csrf_token_default=d091a60db343944596ecc78158dbd803; passport_csrf_token=d091a60db343944596ecc78158db…39e3413233eeb2352dab3c; sessionid=b1b7f87b0839e3413233eeb2352dab3c; sessionid_ss=b1b7f87b0839e3413233eeb2352dab3c; sid_ucp_v1=1.0.0-KDhmOGQ5MzEwYmRhZTBlYzQ4NDMwMjU1ZWFjMGU1NDI0NjhhZmU2OTYKIAiGiNbA4OXKvGEQspfliwYYswsgDDCyl-WLBjgBQOsHEAMaBm1hbGl2YSIgYjFiN2Y4N2IwODM5ZTM0MTMyMzNlZWIyMzUyZGFiM2M; ssid_ucp_v1=1.0.0-KDhmOGQ5MzEwYmRhZTBlYzQ4NDMwMjU1ZWFjMGU1NDI0NjhhZmU2OTYKIAiGiNbA4OXKvGEQspfliwYYswsgDDCyl-WLBjgBQOsHEAMaBm1hbGl2YSIgYjFiN2Y4N2IwODM5ZTM0MTMyMzNlZWIyMzUyZGFiM2M; store-idc=maliva; store-country-code=fr' > results-$i.json;
  done

**Comment by boogheta** [comment]
https://gist.github.com/boogheta/6babff3c34714d28814295729cbed22a
