### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by jlbreeeez** [medialab/minet#372]
Forewords  : sorry, new on GitHub, and I'm not sure it is the appropriate place to post my question... Is it ? 

Hi, 
First, thank you for the tool which will help me a lot in my research !
I got a problem, which I think is not that complicated, but when I run Minet in order to get the "friends" of the twitter_users contained in the data_users.csv file, I don't manage to get access to the file : "Permission Denied"... I tried to open the CMD as an Administrator but it didn't solve the problem. 
Can you help me ? 

![Capture](https://user-images.githubusercontent.com/94457165/143453649-ed3c24da-92d5-4fa7-9dc8-28e1dbfc02a8.JPG)

**Comment by Yomguithereal** [comment]
Hello @jlbreeeez, what OS are you running your command on? It seems your shell does not have the right to read from the `data_users.csv` file. Maybe it belong to another user? What information gives you `ls -lh data_users.csv`?

**Comment by jlbreeeez** [comment]
Hi Yomguithereal, thank's for answering so swiftly :-)
I'm running my commands on Debian, and the command you sent me gave me : 
![image](https://user-images.githubusercontent.com/94457165/143456103-67f69d79-f335-405a-a8a2-b67d3e4b8754.png)

**Comment by jlbreeeez** [comment]
ps : It is a Debian shell, but my all machine is running on Windows

**Comment by Yomguithereal** [comment]
@jlbreeeez the dashed line on the left seems to indicate that you have no rights over this file. Your shell cannot do anything with it. Unfortunately I have no knowledge of using a debian shell on windows so I am afraid I cannot help you further. You might want to try using `sudo` before your command to see if it works.

**Comment by Yomguithereal** [comment]
If you are using Anaconda on windows, or another mean of running Jupyter notebooks, you might want to try this trick to run shell commands from a notebook: https://github.com/medialab/minet/blob/master/cookbook/notebooks/Minet%20in%20a%20Jupyter%20notebook.ipynb

**Comment by jlbreeeez** [comment]
Hi @Yomguithereal, I eventually find out how it works : 
> First, the file must be in the appropriate directoryn which is the one associated with the Debian Shell on my machine (in y case, the path seems like : C:\Users\Utilisateur\AppData\Local\Packages\TheDebianProject.DebianGNULinux_76v4gfsz19hv4\LocalState\rootfs\home\{my_Debian_username})
> Then I just had to write : chmod +rwx filename
Then it worked !
![image](https://user-images.githubusercontent.com/94457165/143474863-80524834-d943-45a8-81cd-11ae36665895.png)
