### ISSUE TITLE
Scrap Retweet

### ISSUE THREAD

**Issue by jlbreeeez** [medialab/minet#373]
Hi !
As far as I see, the tool is quite complete ! But is there any way to get the tweets retweeted by a user ? 

Thx !

**Comment by Yomguithereal** [comment]
Hello @jlbreeeez, unfortunately this is not as easy as it seems.

1. you cannot get this info by scraping
2. you cannot get this info using Twitter API v1 (although the docs says you can, but it is in fact a lie)
3. you cannot do so using Twitter API v2 either.

What is possible:

* Retrieve a user's latest 3200 tweets (using minet tw user-tweets, for instance), and filter out those which are retweets in those.
* Retrieve retweets for a specific tweet (using API v2, currently not implemented in minet but on the roadmap).

**Comment by jlbreeeez** [comment]
All right i will try this right now ;) thank you very much !
