### ISSUE TITLE
Twitter scrape: systematic TwitterGuestTokenError with v0.56.2 or v0.56.1

### ISSUE THREAD

**Issue by paulgirard** [medialab/minet#384]
As in #382 I experience systematic TwitterGuestTokenError exceptions. Was not the case a few weeks ago.
I didn't test other versions than 0.56.1 and 0.56.2.

Looks like we need to review the twitter scrape heuristic.
I will try to have a look later today or tomorrow.

**Comment by Yomguithereal** [comment]
I think #382 displays a similar problem.

**Comment by Yomguithereal** [comment]
As a hint: snscrape seemed to have struggled with the same issue as shown in there commits: https://github.com/JustAnotherArchivist/snscrape/commits/master

It seems to be tied to the user agent somehow? I did not investigated much.

**Comment by paulgirard** [comment]
I started looking at this.

A first quick fix consists in using the API route used in SNScrape as a secondary guest token retrievale method (
I have no clue if the first method is definitely dead or can still sometimes work).
Then I propose to add a method to set the guest token before searching to let the lib users decide to store the guest token and reuse it. Unless you think the lib should do the token storage directly ?
I nevertheless need to go a little bit deeper on this to see on to deprecate a guest token.

I'll share my solution through a PR as soon as I have something sharable.

**Comment by Yomguithereal** [comment]
I think porting to the newest api call should be preferred (as is done here: https://github.com/JustAnotherArchivist/snscrape/commit/0336ce13edbd195b3e91487061a0e7a2857f0c68 ?). It would very much complexify the command to need to get the token by different means and to require caching it. It would be nice if this could remain stateless. But I have no visibility on this. Maybe it's not possible anymore :'(

**Comment by paulgirard** [comment]
It can be stateless and replace the previous method.
But we can still propose to reuse a token for people who want to do it.
I will simplify my edit to just the method to get the guest token for now and we will see if that suffice.
