### ISSUE TITLE
Get Retweeters

### ISSUE THREAD

**Issue by jlbreeeez** [medialab/minet#403]
Hi, thanks for the last release, I'm glad to see there is a Retweeters tool but I went through some issues with it... for a few days.. 
I may not understood how it should implemented ? 
I run it and I get this error : 
![image](https://user-images.githubusercontent.com/94457165/156603093-6e9072a3-be41-4f9d-8b00-bc98d9d5a79c.png)
May someone who manage with it help me ? 

Thank you

**Comment by Yomguithereal** [comment]
Can you make sure all the lines of your input csv file always has the same number of columns?

**Comment by jlbreeeez** [comment]
Hi Yomguithereal
I checked, but I'm sure
There is only one column which is called "Id"

I even tried to implement the query with on Id only, but I get the same error...

**Comment by Yomguithereal** [comment]
Can you give me a minimal example csv file I can use to run tests on my end and see what's the issue?

**Comment by jlbreeeez** [comment]
Hi again Yomguithereal, sorry for the time I took for answering.. I'm confused, I think I just went wrong when creating my .csv file, because my id where note formated in a good way.. It seems to work now (still runing...) Thank you for you help :D

**Comment by jlbreeeez** [comment]
It seems to be stuck... I've tried with a 500-rows csv file, then with a 20-rows csv file, but it seems to be stuck ....
![image](https://user-images.githubusercontent.com/94457165/156991479-5f4f9750-a5e5-4c43-bae0-73cfc829a1b4.png)

**Comment by jlbreeeez** [comment]
[tweets_bowl1.csv](https://github.com/medialab/minet/files/8195836/tweets_bowl1.csv)

**Comment by jlbreeeez** [comment]
![image](https://user-images.githubusercontent.com/94457165/156992516-7df3b575-5cbe-4bd6-b56d-419105314e87.png)
This is the error I eventually get

**Comment by jlbreeeez** [comment]
I opened the file my first tweet extraction gave me, I filter the rows that didn't seem to have relevant datas, wich finally gave me 20 rows (the limit I used for scrapping my first batch of tweets)
Should I use the raw file Minet gives me after retriving the first batch of tweet ?

**Comment by Yomguithereal** [comment]
What did you use to open the file to filter it? It seems the program or script you used corrupted your csv data.

**Comment by jlbreeeez** [comment]
well... I used Excel :/

**Comment by Yomguithereal** [comment]
Excel is notoriously bad at dealing with csv files and often completely destroy them, case in point :) I strongly advise you to use something like LibreOffice instead, or even a text editor to edit those files. If you still want to go with Excel, the good way™ to go is to open an empty spreadsheet and use the "import data" utility, then double check you are using `,` as separator and `"` as escaper char and to use the UTF-8 encoding (not windows cp-1252 like Excel urges you to do). Then you'll have a true spreadsheet containing the data you will then need to export to the correct CSV format when saving so you can feed it to minet or other python scripts.

**Comment by jlbreeeez** [comment]
Okaay thank you ! I tried like that and it woked (for a small amount of  tweets)
What is the number-of-tweets limit you would advise me to respect ? something like <100 <500 <1000 ? 
I have quite a big amount of tweet for which I would like to know who retweeted them... (last question, I swear ^^)

**Comment by Yomguithereal** [comment]
It depends mostly on your skills, your means (server, the necessary disk space etc.), the time you have and the mean number of retweets your tweets have usually. The tool can get you very far, we personally collect millions of tweets with it (for larger scales we have another tool called gazouilloire). Let's say the tool is not the limit here but more the API's limits and the time you are willing to spend.

**Comment by jlbreeeez** [comment]
Okay thank you for all your comments and very helpfull message ;) I found the tool eventually quite intuitive ! congrat's
jlbreeeez
