### ISSUE TITLE
[Youtube channel-videos] Check whether there are more available fields that could be returned

### ISSUE THREAD

**Issue by boogheta** [medialab/minet#428]
currently the command only outputs minimal info:
```channel,video_id,published_at,channel_id,title,description,channel_title```

It would be useful to collect more fields such as nb_comments or likes for instance if they are available

**Comment by Yomguithereal** [comment]
The docs here: https://developers.google.com/youtube/v3/docs/playlistItems/list seems to indicate we could add `contentDetails` to the part param et retrieve the video duration and whether it has subtitles, but we won't get more (no stats, I am afraid).
