### ISSUE TITLE
[telegram] collect data public channels?

### ISSUE THREAD

**Issue by boogheta** [medialab/minet#443]
explore possibilities : 
- via open source apps https://telegram.org/apps
- via web preview ex: https://t.me/s/trottasilvano (with infinite scrollup)

**Comment by shadenshabayek** [comment]
P.S. this app is one of the very few that show the number of **"views"** for everyone (not only the publisher of the post or message), hence could be very interesting to address questions related to the link between audience (exposure) and engagement
