### ISSUE TITLE
Display error message when gh api is rate limited for install script

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/minet#451]
If we are being rate-limited the latest tag cannot be found and the downloaded zip file is corrupted hence failing unzipping later on.

**Comment by kat-kel** [comment]
Message:
The zipped file was not able to be downladed because the rate limit of GitHub's API was reached. Please wait a few moments and launch the command again.

**Comment by kat-kel** [comment]
@Yomguithereal I pushed a fix to the branch install-gh-api
