### ISSUE TITLE
minet fetch max-redirect error on working url

### ISSUE THREAD

**Issue by boogheta** [medialab/minet#489]
https://documents1.worldbank.org/curated/en/954721529638270108/text/Romania-Country-partnership-framework-for-the-period-FY19-FY23.txt

**Comment by Yomguithereal** [comment]
I cannot reproduce. I get a direct `200` when hitting the url with minet/curl/browser. Is this perchance the final url and not the one that triggered the redirection?

**Comment by boogheta** [comment]
Ha it could be, I will ask him to send me his full download log file to check

**Comment by boogheta** [comment]
here's the original url: http://documents.worldbank.org/curated/en/805841545925652368/text/Zambia-Country-Partnership-Framework-for-the-Period-FY19-FY23.txt

When using curl -IL, I get only 3 redirections steps, but with a weird back & forth on http/https using briefly http2 then back to http1.1:
- http://documents.worldbank.org/curated/en/805841545925652368/text/Zambia-Country-Partnership-Framework-for-the-Period-FY19-FY23.txt => HTTP/1.1 301 Moved Permanently
- https://documents.worldbank.org/curated/en/805841545925652368/text/Zambia-Country-Partnership-Framework-for-the-Period-FY19-FY23.txt => HTTP/2 302
- http://documents1.worldbank.org/curated/en/805841545925652368/text/Zambia-Country-Partnership-Framework-for-the-Period-FY19-FY23.txt => HTTP/1.0 302 Moved Temporarily
- https://documents1.worldbank.org/curated/en/805841545925652368/text/Zambia-Country-Partnership-Framework-for-the-Period-FY19-FY23.txt => HTTP/1.1 200 OK

**Comment by Yomguithereal** [comment]
It works on the latest version of minet. Maybe something changed on our side or on their side. (The url returns garbled mojibake on a web browser anyway...)
