### ISSUE TITLE
[retweeters] KeyError: 'url'

### ISSUE THREAD

**Issue by tloops329384** [medialab/minet#512]
Hi, 
when I try to retrieve the retweeters list from a file containing tweets previously extracted from Twitter using minet scrapper, I get this error after scanning a few tweets from my list (after 7, 10, or 30 tweets scanned... it depend of the database...). Does anyone encountered this error before ? Thanks for helping :-)
![image](https://user-images.githubusercontent.com/112090034/207030293-f8466c42-b008-46b1-9155-05ac5cbd5345.png)

**Comment by tloops329384** [comment]
Here above, I started by retrieving a list of 60 tweets containing the keyword "rugby". The tweets list is called test7.csv. 
Then, I launch a command for retrieving the users who retweeted these tweets contained in test7.csv... and it doesn't work after 15 tweets scanned among 60. 
I tried with other queries than "rugby"... every time it can't go further than 10, 7, 8, 15... tweets. Depend on the queries.

**Comment by Yomguithereal** [comment]
Hello @tloops329384. Can you indicate what version of minet you are using (you can get this info with `minet --version`) and make sure you have the latest one installed (`0.66.0`)? Because this looks like a bug that was fixed some time ago.

**Comment by tloops329384** [comment]
Hello @Yomguithereal, thank you for answering so swiftly. I'm indeed NOT on version 0.66.0. Nonetheless, when I try to upgrade my minet on kali I'm still on version 0.61.5 ! Shall uninstall and reinstall all minet ?

**Comment by Yomguithereal** [comment]
How did you upgrade? Are you using the pip version or the standalone one? If using pip did you use the `-U` flag?

**Comment by tloops329384** [comment]
using minet as a CLI tool on a kali terminal

**Comment by Yomguithereal** [comment]
This should do the trick. If it does not try uninstall/install again indeed. Another issue might be that you have installed both the standalone & the pip version and one is taking precedence over the other, making your upgrade appear as failed.

**Comment by tloops329384** [comment]
Hi @Yomguithereal , I just wanted to tell you that it works with the 0.66.0 :-) AND also to say THANK YOU SO MUCH for the 0.66.1 which is much more ergonomic when a bug in the dataset occurs :D Wow. 
I can only encourage you and your team whose work I appreciate.
