### ISSUE TITLE
HEAD queries refused by some domains

### ISSUE THREAD

**Issue by boogheta** [medialab/minet#52]
eBay refuses HEAD (they return a header Allow: GET) queries and redirects to a wrong page with infinite redirection when used
Example : 
https://ebay.us/BUkuxU should get to https://www.ebay.com/itm/253189196428
but it goes to http://pages.ebay.com/messages/page_not_responding.html through https://pages.ebay.com/messages/page_not_responding.html and https://www.ebay.com/n/error?statuscode=500

Gotta love the web!

**Comment by Yomguithereal** [comment]
Let me die in peace now.

**Comment by Yomguithereal** [comment]
I guess the only course of action we have left here is to switch to `GET` requests without fetching the body.

**Comment by Yomguithereal** [comment]
It should also be noted that the redirect will fail if you don't spoof UA...

**Comment by Yomguithereal** [comment]
I changed default method to `GET`, and `spoof_ua` is now on by default. `follow_meta_refresh` still `False` by default because it remains quite costly.
