### ISSUE TITLE
Twitter scraper recent problems

### ISSUE THREAD

**Issue by BasCR-hub** [medialab/minet#525]
On Jan 12, the command line tool to scrape twitter stopped working (it worked on Jan. 11th), raising a TwitterPublicAPIInvalidResponseError.

![Screenshot from 2023-01-13 09-59-46](https://user-images.githubusercontent.com/63452988/212280193-19cfaa64-d7f1-4e6b-a650-6fcc7860520c.png)

The equivalent Python Scraper also stopped working (doesn't raise an issue on a Jupyter, only runs forever.)

**What I tried** 

In the [api_scraper script](https://github.com/medialab/minet/blob/master/minet/twitter/api_scraper.py), tried to replace :

TWITTER_PUBLIC_SEARCH_ENDPOINT = "https://twitter.com/i/api/2/search/adaptive.json"  

with 

TWITTER_PUBLIC_SEARCH_ENDPOINT = "https://api.twitter.com/2/search/adaptive.json"  

As this is what a quick analysis of the network traffic showed as being the API used, but it does not work.

Any help would be much appreciated !

**Comment by Yomguithereal** [comment]
Hello @BasCR-hub. We also noticed this problem on our end yesterday but did not have time to investigate as of yet. We hope there is an easy solution but the current state of Twitter does not inspire an unyielding hope.

**Comment by Yomguithereal** [comment]
Ok, I cannot explain why but the scraper works on my end today. Do you still reproduce on your end right now?

**Comment by boogheta** [comment]
I do :(

**Comment by Yomguithereal** [comment]
For now the score is 3 people cannot reproduce, 2 can. It certainly starts to feel like a network/load balancing issue.

**Comment by BasCR-hub** [comment]
Just tried, still not working on my end. In any case, thank you for your quick response !

**Comment by Yomguithereal** [comment]
@BasCR-hub can I ask you to log things around here: https://github.com/medialab/minet/blob/master/minet/twitter/api_scraper.py#L322 or here https://github.com/medialab/minet/blob/master/minet/twitter/api_scraper.py#L364 and see if you can spot some obvious thing about the returned payloads indicating the problem?

**Comment by BasCR-hub** [comment]
@Yomguithereal I get a 'Sorry, that page does not exist' error (which is strange if your colleagues are getting it to work but I'm way out of my depth here, don't have the slightly clue as to what could be going on). 

![Screenshot from 2023-01-13 15-16-45](https://user-images.githubusercontent.com/63452988/212340873-ce88e819-f3b1-4bce-9fc1-9400950b1040.png)

**Comment by Yomguithereal** [comment]
There seem to be similar reports on a lot of third party tools hitting the API currently. It might be a technical hiccup from Twitter that we can do nothing about unfortunately :'(

**Comment by BasCR-hub** [comment]
Duly noted, thank you.

**Comment by cgillett** [comment]
I have this issue as well.

**Comment by emmabonuttidagostini** [comment]
I have the same issue as well, I have tried from different WiFi connections as suggested but still not working :/

**Comment by cgillett** [comment]
Using Chrome's developer tools, I looked at a network request to Twitter's public search API. I copied it as CURL:

`curl 'https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_verified_type=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_ext_limited_action_results=false&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_ext_collab_control=true&include_ext_views=true&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=from%3A%40elonmusk%20filter%3Anativeretweets&result_filter=image&count=20&query_source=typed_query&pc=1&spelling_corrections=1&include_ext_edit_control=true&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2CbirdwatchPivot%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe' \
  -H 'authority: api.twitter.com' \
  -H 'accept: */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'authorization: Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA' \
  -H 'cookie: guest_id_marketing=v1%3A167381515046087179; guest_id_ads=v1%3A167381515046087179; personalization_id="v1_7QQYO7ReFJQ5XSsbUMWjQA=="; guest_id=v1%3A167381515046087179; ct0=d1b3c599ff5033dc05f78e2c741c2f7b; _ga=GA1.2.1959818046.1673815152; _gid=GA1.2.775789968.1673815152; gt=1614723899178078211' \
  -H 'origin: https://twitter.com' \
  -H 'referer: https://twitter.com/' \
  -H 'sec-ch-ua: "Not?A_Brand";v="8", "Chromium";v="108", "Google Chrome";v="108"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36' \
  -H 'x-csrf-token: d1b3c599ff5033dc05f78e2c741c2f7b' \
  -H 'x-guest-token: 1614723899178078211' \
  -H 'x-twitter-active-user: yes' \
  -H 'x-twitter-client-language: en' \
  --compressed`

I then pasted this CURL into Insomnia (a Postman alternative). This request was successful!

<img width="1143" alt="Screenshot 2023-01-15 at 3 41 18 PM" src="https://user-images.githubusercontent.com/4927095/212568736-9c5f436c-a0b1-4655-84e1-d799163db200.png">

Insomnia has a feature that lets you generate code snippets for a request. Using that feature, I generated this code snippet:

`import requests

url = "https://api.twitter.com/2/search/adaptive.json"

querystring = {"include_profile_interstitial_type":"1","include_blocking":"1","include_blocked_by":"1","include_followed_by":"1","include_want_retweets":"1","include_mute_edge":"1","include_can_dm":"1","include_can_media_tag":"1","include_ext_has_nft_avatar":"1","include_ext_is_blue_verified":"1","include_ext_verified_type":"1","skip_status":"1","cards_platform":"Web-12","include_cards":"1","include_ext_alt_text":"true","include_ext_limited_action_results":"false","include_quote_count":"true","include_reply_count":"1","tweet_mode":"extended","include_ext_collab_control":"true","include_ext_views":"true","include_entities":"true","include_user_entities":"true","include_ext_media_color":"true","include_ext_media_availability":"true","include_ext_sensitive_media_warning":"true","include_ext_trusted_friends_metadata":"true","send_error_codes":"true","simple_quoted_tweet":"true","q":"from:@elonmusk filter:nativeretweets","result_filter":"image","count":"20","query_source":"typed_query","pc":"1","spelling_corrections":"1","include_ext_edit_control":"true","ext":"mediaStats,highlightedLabel,hasNftAvatar,voiceInfo,birdwatchPivot,enrichments,superFollowMetadata,unmentionInfo,editControl,collab_control,vibe"}

payload = ""
headers = {
    "cookie": "guest_id_marketing=v1%3A167381515046087179; guest_id_ads=v1%3A167381515046087179; personalization_id="v1_7QQYO7ReFJQ5XSsbUMWjQA=="; guest_id=v1%3A167381515046087179; ct0=d1b3c599ff5033dc05f78e2c741c2f7b; _ga=GA1.2.1959818046.1673815152; _gid=GA1.2.775789968.1673815152; gt=1614723899178078211",
    "authority": "api.twitter.com",
    "accept": "*/*",
    "accept-language": "en-US,en;q=0.9",
    "authorization": "Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA",
    "origin": "https://twitter.com",
    "referer": "https://twitter.com/",
    "sec-ch-ua": ""Not?A_Brand";v="8", "Chromium";v="108", "Google Chrome";v="108"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": ""macOS"",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-site",
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
    "x-csrf-token": "d1b3c599ff5033dc05f78e2c741c2f7b",
    "x-guest-token": "1614723899178078211",
    "x-twitter-active-user": "yes",
    "x-twitter-client-language": "en"
}

response = requests.request("GET", url, data=payload, headers=headers, params=querystring)

print(response.text)`

Unfortunately, running that code gives the same "page not found" error:

![Screenshot 2023-01-15 at 3 42 35 PM](https://user-images.githubusercontent.com/4927095/212568781-eb791881-5fc8-4200-8dd4-52781ccfd390.png)

**Comment by Pclanglais** [comment]
I'm not surprised: some of the tokens are probably generated for one session only.

At this point I think the main issue is whether this is only a bug (definitely possible as twitter tech teams are running very lean) or something more intentional. Research APIs are still working as far as I know.

**Comment by SuperMobile9** [comment]
I've been trying for days, and I always get the same error :(

**Comment by Yomguithereal** [comment]
My current problem is that I cannot reproduce the error, which makes it impossible to solve. I might have access to a computer reproducing the error in the next days hopefully. Some people tend to say that this is related to TLS protocol changes from the API itself but I cannot confirm yet.

**Comment by Pclanglais** [comment]
There seems to be an intentional "crackdown" of APIs on the part of Twitter going on, so I'm not sure there is much that can be done (aside from the selenium/cookie route but it will never be at the same scale). I can only confirm that the research API is still working even on a connection where Minet fails.

**Comment by Yomguithereal** [comment]
Regarding this particular issue I cannot say with confidence that this is intentional because it is very hard to pinpoint why some connections work and other don't. It does not look like the API "crackdown" affecting TwitterDeck and such. It looks more like they broke something and they might not even be aware that they did, which is not surprising regarding the current state of their operation.

**Comment by charlesdedampierre** [comment]
Hi all, 

I confirm it is not working on my end either since yesterday morning, here is what I get, 

<img width="1046" alt="Screenshot 2023-01-18 at 11 38 46" src="https://user-images.githubusercontent.com/49554507/213150327-cf6b5e15-d687-4c81-be63-927e6c52afc6.png">

**Comment by boogheta** [comment]
Just leaving that here https://twitter.com/TwitterDev/status/1615405842735714304

**Comment by Pclanglais** [comment]
I've down some further trial on different servers in the US, France and Italy. I've got each time the same message: minet.twitter.exceptions.TwitterPublicAPIInvalidResponseError

**Comment by Yomguithereal** [comment]
In our offices, some outgoing IP address work, others don't lol

**Comment by Yomguithereal** [comment]
A bunch of related issues:

* https://github.com/mikf/gallery-dl/issues/3522
* https://github.com/JustAnotherArchivist/snscrape/issues/675
* https://github.com/JustAnotherArchivist/snscrape/issues/647

**Comment by paulgirard** [comment]
I searched a little bit around the issue.
From my observation of the public web client, I note that :

- the search API URL is https://api.twitter.com/2/search/adaptive.json (and not https://twitter.com/i/api/2/search/adaptive.json)
- there is CSRF token in the call to the search API which is also stored in the ct0 cookie field
- the CSRG is generated by the client for the auth call (guest/activate.json) but I couldn't understand how to generate it

I could get some tweets from an insomnia session by adding those csrf header and cookie ct0 field and using any of the two url (https://twitter.com/i/api/2/search/adaptive.json or https://api.twitter.com/2/search/adaptive.json).

Hope this little something will help someone.

**Comment by paulgirard** [comment]
> Using Chrome's developer tools, I looked at a network request to Twitter's public search API. I copied it as CURL:
> 
> `curl 'https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&include_ext_has_nft_avatar=1&include_ext_is_blue_verified=1&include_ext_verified_type=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_ext_limited_action_results=false&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_ext_collab_control=true&include_ext_views=true&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&include_ext_sensitive_media_warning=true&include_ext_trusted_friends_metadata=true&send_error_codes=true&simple_quoted_tweet=true&q=from%3A%40elonmusk%20filter%3Anativeretweets&result_filter=image&count=20&query_source=typed_query&pc=1&spelling_corrections=1&include_ext_edit_control=true&ext=mediaStats%2ChighlightedLabel%2ChasNftAvatar%2CvoiceInfo%2CbirdwatchPivot%2Cenrichments%2CsuperFollowMetadata%2CunmentionInfo%2CeditControl%2Ccollab_control%2Cvibe' \ -H 'authority: api.twitter.com' \ -H 'accept: */*' \ -H 'accept-language: en-US,en;q=0.9' \ -H 'authorization: Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA' \ -H 'cookie: guest_id_marketing=v1%3A167381515046087179; guest_id_ads=v1%3A167381515046087179; personalization_id="v1_7QQYO7ReFJQ5XSsbUMWjQA=="; guest_id=v1%3A167381515046087179; ct0=d1b3c599ff5033dc05f78e2c741c2f7b; _ga=GA1.2.1959818046.1673815152; _gid=GA1.2.775789968.1673815152; gt=1614723899178078211' \ -H 'origin: https://twitter.com' \ -H 'referer: https://twitter.com/' \ -H 'sec-ch-ua: "Not?A_Brand";v="8", "Chromium";v="108", "Google Chrome";v="108"' \ -H 'sec-ch-ua-mobile: ?0' \ -H 'sec-ch-ua-platform: "macOS"' \ -H 'sec-fetch-dest: empty' \ -H 'sec-fetch-mode: cors' \ -H 'sec-fetch-site: same-site' \ -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36' \ -H 'x-csrf-token: d1b3c599ff5033dc05f78e2c741c2f7b' \ -H 'x-guest-token: 1614723899178078211' \ -H 'x-twitter-active-user: yes' \ -H 'x-twitter-client-language: en' \ --compressed`
> 
> I then pasted this CURL into Insomnia (a Postman alternative). This request was successful!
> 
> <img alt="Screenshot 2023-01-15 at 3 41 18 PM" width="1143" src="https://user-images.githubusercontent.com/4927095/212568736-9c5f436c-a0b1-4655-84e1-d799163db200.png">
> 
> Insomnia has a feature that lets you generate code snippets for a request. Using that feature, I generated this code snippet:
> 
> `import requests
> 
> url = "https://api.twitter.com/2/search/adaptive.json"
> 
> querystring = {"include_profile_interstitial_type":"1","include_blocking":"1","include_blocked_by":"1","include_followed_by":"1","include_want_retweets":"1","include_mute_edge":"1","include_can_dm":"1","include_can_media_tag":"1","include_ext_has_nft_avatar":"1","include_ext_is_blue_verified":"1","include_ext_verified_type":"1","skip_status":"1","cards_platform":"Web-12","include_cards":"1","include_ext_alt_text":"true","include_ext_limited_action_results":"false","include_quote_count":"true","include_reply_count":"1","tweet_mode":"extended","include_ext_collab_control":"true","include_ext_views":"true","include_entities":"true","include_user_entities":"true","include_ext_media_color":"true","include_ext_media_availability":"true","include_ext_sensitive_media_warning":"true","include_ext_trusted_friends_metadata":"true","send_error_codes":"true","simple_quoted_tweet":"true","q":"from:@ElonMusk filter:nativeretweets","result_filter":"image","count":"20","query_source":"typed_query","pc":"1","spelling_corrections":"1","include_ext_edit_control":"true","ext":"mediaStats,highlightedLabel,hasNftAvatar,voiceInfo,birdwatchPivot,enrichments,superFollowMetadata,unmentionInfo,editControl,collab_control,vibe"}
> 
> payload = "" headers = { "cookie": "guest_id_marketing=v1%3A167381515046087179; guest_id_ads=v1%3A167381515046087179; personalization_id="v1_7QQYO7ReFJQ5XSsbUMWjQA=="; guest_id=v1%3A167381515046087179; ct0=d1b3c599ff5033dc05f78e2c741c2f7b; _ga=GA1.2.1959818046.1673815152; _gid=GA1.2.775789968.1673815152; gt=1614723899178078211", "authority": "api.twitter.com", "accept": "_/_", "accept-language": "en-US,en;q=0.9", "authorization": "Bearer AAAAAAAAAAAAAAAAAAAAANRILgAAAAAAnNwIzUejRCOuH5E6I8xnZz4puTs%3D1Zv7ttfk8LF81IUq16cHjhLTvJu4FA33AGWWjCpTnA", "origin": "https://twitter.com", "referer": "https://twitter.com/", "sec-ch-ua": ""Not?A_Brand";v="8", "Chromium";v="108", "Google Chrome";v="108"", "sec-ch-ua-mobile": "?0", "sec-ch-ua-platform": ""macOS"", "sec-fetch-dest": "empty", "sec-fetch-mode": "cors", "sec-fetch-site": "same-site", "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36", "x-csrf-token": "d1b3c599ff5033dc05f78e2c741c2f7b", "x-guest-token": "1614723899178078211", "x-twitter-active-user": "yes", "x-twitter-client-language": "en" }
> 
> response = requests.request("GET", url, data=payload, headers=headers, params=querystring)
> 
> print(response.text)`
> 
> Unfortunately, running that code gives the same "page not found" error:
> 
> ![Screenshot 2023-01-15 at 3 42 35 PM](https://user-images.githubusercontent.com/4927095/212568781-eb791881-5fc8-4200-8dd4-52781ccfd390.png)

I confirm.
Any python or javascript-node version of the query failed where the insomnia OR Curl version worked...

**Comment by cgillett** [comment]
Out of curiosity, is there anyone here who gets this error and is very confident that they have _not_ been abusing the Twitter search API? I get this bug on one machine that has definitely been abusive, but on another machine that has not (some versions, same everything - as far as I can tell) I don't get this bug.

I think it's likely that this bug represents a sort of IP ban + some sophisticated method for detecting requests coming from python's request library.

There must be something slightly distinctive about requests coming from python's requests library. For example I know that, by default, python's requests library adds certain headers; I tried modifying these default headers - it makes no difference. Maybe it's something to do with encoding? I searched "request works in curl but not python requests" and saw some answers about passing the payload as a string instead of a dict.

Another possibility is that when they changed the API endpoint they added some sort of redirect/routing that curl can handle but that messes up python requests library.

**Comment by emmabonuttidagostini** [comment]
@cgillett I have tried with several PCs, some of which had never used MINET before, and I get the bug in all of them :/

**Comment by Yomguithereal** [comment]
minet does not use `requests`. But it uses urllib3 which is also used by `requests` if I recall correctly. minet also spoofs its call so that it cannot trivially be detected as a typical curl/requests/whatever call (it can still be done of course, TLS cipher detection is a good example of sneaky countermeasure that seems to be happening there also). I can reproduce the issue on computer and IP adresses that never used minet, randomly. I think the IP bans are more random (in our university we have 3 outgoing IPs, all three have been hitting Twitter very hard for years, but only one of them seems banned). So far I can say there are at least five different problem:

* IP bans
* TLS cipher bans (typically `requests` on some OSes & some version of OpenSSL, it also affects similar libs in node.js etc.)
* CSRF enforcement (randomly again)
* Inconsistent response wrt GET query and POST data randomly from one computer to the next (related to 401 response codes)
* Erratic response from the API with empty results sometimes and inconsistent metrics returned (even on the website sometimes)

It certainly looks like a crackdown on third-party Twitter clients and well-known scrapers combined with a technical shitshow happening in the background. It's possible that we will find a solution in the near future, but currently my stance is to wait a little bit for things to cool off and assess what can realistically be done (it can mean switching to more complex technologies relying on headless browser and such).

**Comment by BasCR-hub** [comment]
Being on a deadline for a research project, I've been looking around for possible alternatives and I found that [snscrape](https://github.com/JustAnotherArchivist/snscrape)'s Twitter scraper was still working on my end. No clue as to why, but maybe useful as an inspiration ?

**Comment by Yomguithereal** [comment]
As far as I know, `snscrape` addressed the TLS Cipher countermeasures that can fix some of the problems beforementioned. It does not work on my end however and does not fix the other issues, so this is still mostly random at this point.

**Comment by unixdevil** [comment]
> e API currently. It might be a technical hiccup from Twitter that we can do nothing about unfortunately :'(

hasn't urlib had an  updated in the past days ?

**Comment by Yomguithereal** [comment]
Hello everyone, I have installed the TLS Ciphers countermeasures from snscrape into minet. It is released as part of the v0.66.2 version and should fix the issue for some of you hopefully (I can confirm that, on our side, it fixed the problem for 7 people, i.e. everyone). I am sure some of you will still have issues in which case, please come back to this thread so we can try to fix the remaining issues.

**Comment by cgillett** [comment]
This have solve the issue for me. Thank you!!
