### ISSUE TITLE
Free api support for twitter will stop on February 9

### ISSUE THREAD

**Issue by Xteom** [medialab/minet#535]
I suppose this will affect minet, not sure if it goes here. 
https://twitter.com/twitterdev/status/1621026986784337922?s=48&t=KgYRwbw4ytMz8YhZFxy3dg

**Comment by Yomguithereal** [comment]
It should indeed affect minet's command relying on API access yes. I guess that the tool will continue to work for people paying the fee though. Else you can still use the scraping command that is not affected (yet) by this last elno shenanigan.
