### ISSUE TITLE
Jsondecoder error when rthere is no response 

### ISSUE THREAD

**Issue by Iniitiator** [medialab/minet#549]
I tried minet scrapper and it ran well, when deployed it to a container fro my prod env, this json decoder error of Expecting value was there, the fact was there is no response from the URL generated, but any such error was not there when ran locally, please fix this, as it creates a chaos when trying it out, though minet is a good library to use

**Comment by Yomguithereal** [comment]
Hello @Iniitiator,

> I tried minet scrapper and it ran well

Which one? `minet` exposes a large variety of different scrapers. Are we speaking about the Twitter one, for instance?

> when deployed it to a container fro my prod env, this json decoder error of Expecting value was there, the fact was there is no response from the URL generated, but any such error was not there when ran locally, please fix this, as it creates a chaos when trying it out, though minet is a good library to use

This is all really unclear and I don't understand what you did, nor do I have any way to reproduce your issue. This means there is no way I can even attempt to fix it.

**Comment by Iniitiator** [comment]
I tried  the twitter one, acttually when trying to use twitter scrapper, search tweets function in that, then for my custom query which I am passing it, it is throwing the error in few cases when there is no data,else is data is there it is returning the data correctly, if I have to be very clear, the call that is being made in to request_json function in  api_scrapper.py from there you should handle it

**Comment by Yomguithereal** [comment]
It's still not clear and I still have no way to reproduce your issue, nor anything that could help me pinpoint the problem.

Here are things that could help:

1. Pasting the stack trace of the error you observe
2. Giving me the command line you ran
3. Even better, giving me a command line that reproduce your issue without any ambiguity
