### ISSUE TITLE
Towards a more explicit variadicity?

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/minet#557]
Some `minet` commands are variadic/polymorphic for convenience. This means you can call the commands in three different way:

```bash
# 1. You want to execute the command for a single value
minet fetch "https://www.lemonde.fr"

# 2. You want to execute the command for all the values of a csv column
minet fetch url articles.csv

# 3. You want to read said csv file from stdin
xsv search -s url youtube | minet fetch url
```

This is all and well, but to be able to work, `minet` needs to "sniff" the program's stdin to assert whether it comes from a tty and if it's not empty (because some tty always pipe an empty stdin on some unixes etc., whatever). But this causes some issues because if anything is piped through stdin, you won't be able to use application `1.` of the command (i.e. executing a command for a single value only). This is the case, as described by @boogheta when using bash `while` loops for instance (cf. #427).

Here is a proposition of what we could do:

## 1. explicit stdin/stdout piping through the `-` convention

This comes from discussions with @boogheta.

Instead of implicitly reading from the stdin when present and when arg 2 is not given, we would need to indicate it thusly:

```bash
xsv search -s url youtube | minet fetch url -
```

This follows unix conventions as illustrated by complex commands able to consume multiple input streams and having multiple outputs such as `curl` or `wget`.

This has the advantage of enabling fine support of stdin for commands taking multiple input streams such as `url-join`:

```bash
# First input stream from file, second from stdin
xsv search -s url youtube | minet url-join file1.csv col1 - col2
```

But this option has a single disadventage which is that if you type the following:

```bash
xsv search -s url youtube | minet url-parse url
```

you won't use the stdin at all, and will parse a single url being literally `url` since you forgot the `-`. This seems confusing.

## 2. explicit polymorphism

This comes from discussions with @MiguelLaura.

One way to avoid all this is to make the command line fully explicit and tell when we are working on a single value or a CSV file.

To this end we must answer three questions:

1. Do we want that?
2. Which would be the default (single value, or CSV file)
3. What would be the name of the flag toggling the command behavior

@MiguelLaura and myself propose to have single value as default and the flag named `-T/--tabulate`.

This would change our first three examples to:

```bash
# 1. You want to execute the command for a single value
minet fetch "https://www.lemonde.fr"

# 2. You want to execute the command for all the values of a csv column
minet fetch -T url articles.csv
minet fetch --tabulate url articles.csv

# 3. You want to read said csv file from stdin (notice the -T)
xsv search -s url youtube | minet fetch -T url -
```

Here is what the reverse would look like (tabulate as default, with something like `-S/--single` which I find less clear?):

```bash
# 1. You want to execute the command for a single value
minet fetch -S "https://www.lemonde.fr"

# 2. You want to execute the command for all the values of a csv column
minet fetch url articles.csv
minet fetch url articles.csv

# 3. You want to read said csv file from stdin (notice the -T)
xsv search -s url youtube | minet fetch url -
```

What do you think?

---

Input from @jacomyal: if we have an explicit `-S` or `-T` we have a situation where we can have both:

```bash
xsv search -s url youtube | minet fetch -T url
```

and

```bash
xsv search -s url youtube | minet fetch -T url -
```

because there is no ambiguity in command line arity and those are equivalent in what they would do.

**Comment by Yomguithereal** [comment]
I already have input from @MiguelLaura but would like feedback on this from @boogheta @bmaz @paulgirard @kat-kel @inesgrd

**Comment by paulgirard** [comment]
That's an important and necessary discussion.
I think the current situation needs a fix. Whatever the choice made the main issue will be : it's going to break existing deployment and habits.

For the propositions I would vote for explicit. I think it's always a good bet when naming things.
I find it clearer to use an explicit option for the file input (--tabulate) rather than for single value.

Tabulate option could also be called input which is quiet common in Unix comands (I guess ?).
If tabulate is a cute specialized word, I am afraid people might find it awkward. Input is clearer I think.

**Comment by boogheta** [comment]
I like both propositions, but like the explicit one better.
Like @paulgirard I would go towards a more explicit argument -i/--input, that would be an actual argument expecting a filename or `-` and not a flag (since enabling the flag activates the need for an input file anyways).
This would force the positioning of the arg to be next to the filename and would make column the actual query arg.
Beware since there already is a `-i` option for `--inputdir` which I would replace into a `-I`

**Comment by Yomguithereal** [comment]
For now I'd say the winning combination is `-i/--input=file` with optional `-` as stdin. The only issue remaining is the following case where you pipe into minet while forgetting about `-i -`:

```bash
# This will ignore stdin and attempt to fetch the "url" url
xsv search -s url youtube | minet fetch url
```

**Comment by paulgirard** [comment]
One possibility is to create both -i and -s flags and expect a -i set of options by default.
```
minet fetch url 
xsv search -s url youtube | minet fetch url
xsv search -s url youtube | minet fetch -i url
```
would all fail asking for a filename or -

```
minet fetch -i url file.csv
minet fetch url file.csv
xsv search -s url youtube | minet fetch url -
xsv search -s url youtube | minet fetch -i url -
minet fetch -s "http://medialab.sciencespo.fr"
```
Would all work

**Comment by bmaz** [comment]
I prefer the explicit way as well. However `-i/--input` does not refer to a file and can be any type of input. Why not `-f/--file` ?

**Comment by Yomguithereal** [comment]
I think the point was that some unix commands have a -i/-o pair for input/output. But searching a little bit I cannot find an example. grep has -f/—file so it would also make sense in the unix context. @boogheta @paulgirard any example of -i in the wild?

**Comment by kat-kel** [comment]
I also like the more explicit polymorphism proposition. And I like @boogheta 's suggestion of `-i/--input` for standard input from a read file, with the additional flag `-` when piped to minet. I do see, however, that the little `-` flag risks getting overlooked by a user.
```
# 2. You want to execute the command for all the values of a csv column
minet fetch -i articles.csv url
minet fetch --input articles.csv url

# 3. You want to read said csv file from stdin (notice the -i)
xsv search -s url youtube | minet fetch -i - url
```

Things I'd note:
- I share @Yomguithereal 's impression that most users don't pipe a csv column to minet, and therefore I can see the argument that those who do pipe stdin to minet are more likely to also be familiar with the `-` unix convention.
- That being said, I'm not already familiar with the `-` convention. So I'm wondering if there isn't some way to again by explicit there.

**Comment by boogheta** [comment]
@yomguithereal it's not that standard indeed, I looked a bit through the most classical commands and most often `-i` stands for `--ignore` or `--include` or `--insecure` but at least wget does:
```
       -i file
       --input-file=file
           Read URLs from a local or external file.  If - is specified as
           file, URLs are read from the standard input.  (Use ./- to read from
           a file literally named -.)

           If this function is used, no URLs need be present on the command
           line.  If there are URLs both on the command line and in an input
           file, those on the command lines will be the first ones to be
           retrieved.  If --force-html is not specified, then file should
           consist of a series of URLs, one per line.

           However, if you specify --force-html, the document will be regarded
           as html.  In that case you may have problems with relative links,
           which you can solve either by adding "<base href="url">" to the
           documents or by specifying --base=url on the command line.

           If the file is an external one, the document will be automatically
           treated as html if the Content-Type matches text/html.
           Furthermore, the file's location will be implicitly used as base
           href if none was specified.
```

**Comment by Yomguithereal** [comment]
@boogheta & @bmaz argue that stdin is not a file and therfore `--file -` feels weird
