### ISSUE TITLE
User-Agent randomizer from latest popular ones

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/minet#593]
Some links:

- [ ] https://www.useragents.me/api (I don't know the source)
- [ ] https://techblog.willshouse.com/2012/01/03/most-common-user-agents/ (the source seems a bit weak)
- [ ] https://www.whatismybrowser.com/guides/the-latest-user-agent/ (seems more robust but more scraping involved)

A good first issue for the czar (along with https://github.com/medialab/ural/issues/88).

**Comment by boogheta** [comment]
j'achète pour hyphe!

**Comment by Yomguithereal** [comment]
Oui mais monsieur on est en python3 ici. A la rigueur tu pourrais chopper la liste ici ou avoir une commande minet qui te la donne.

**Comment by boogheta** [comment]
sectaire va
