### ISSUE TITLE
Using tweets csv in twitterexplorer 

### ISSUE THREAD

**Issue by lakonis** [medialab/minet#655]
I am trying to use the csv produced by the CLI minet twitter command directly in [twitterexplorer](https://pypi.org/project/twitterexplorer/0.6.2/#description), assuming that it stores the tweets using the twitwi format. From [twitterexplorer's documentation](https://github.com/pournaki/twitter-explorer/blob/master/doc/DOCUMENTATION.md#data-transformation) :

> You can select a previously collected dataset for further analysis from a drop-down menu. If you have your own Twitter dataset, please convert it to the [twitwi csv format](https://github.com/medialab/twitwi) and copy it to the ./data folder.

However, it doesn't seem to work. Can you confirm that the minet twitter command produce a twitwi-formated csv ? Where can I find the structure of the twitwi format ?

Thank you !

**Comment by Yomguithereal** [comment]
Hello @lakonis,

> Can you confirm that the minet twitter command produce a twitwi-formated csv ?

Yes I confirm, I actually maintain [twitwi](https://github.com/medialab/twitwi/) which was developed by my lab for minet and gazouilloire.

> Where can I find the structure of the twitwi format ?

You can find the list of fields there: https://github.com/medialab/twitwi/blob/master/twitwi/constants.py

> I am trying to use the csv produced by the CLI minet twitter command directly

Which command? There are many of them. Note that the scrape subcommand has some additional fields vs. twitwi because it is able to extract things that are not found in the API. Maybe that's your issue. In any case, you should ask @pournaki :)

**Comment by lakonis** [comment]
Thank you for your quick answer!

Yes indeed I use the scrape subcommand, I should have been more precise. If @pournaki can help, it would be great. Otherwise I will remove extra fields according to the list you mentioned.

Thanks again for the great work (minet, twitwi, hyphe,...)

**Comment by Yomguithereal** [comment]
The list of added fields is [here](https://github.com/medialab/minet/blob/master/minet/twitter/constants.py#L15) if this can help you.

**Comment by Yomguithereal** [comment]
I bide thee good luck and shall henceforth close this issue then :)

**Comment by lakonis** [comment]
@Yomguithereal It is worth mentioning here the result of our investigation : the `scrape` subcommand, when used with a query csv file, adds two extra fields to the csv : `id` and `query`, resulting in 2 fields with the same name `id`. It might be relevant to rename the id from the query into `query_id` for instance, so that the `id` would remain the "tweet_id" according to twitwi format.

**Comment by Yomguithereal** [comment]
@lakonis the command "enriches" your input csv file, by concatenating your columns to the tweet ones. You can rename your input columns on your end and/or use the `--select` flag to only keep some columns from the input.

**Comment by lakonis** [comment]
Tout simplement.. Thanks !
