### ISSUE TITLE
Twitter search is now being rate limited

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/minet#702]

**Comment by Yomguithereal** [comment]
20 calls per minute seems to be a safe spot. Will try to increase it further later (50 demonstrably fails though).

**Comment by Pclanglais** [comment]
Thanks! Each call per minute include a batch of tweets or only one tweets?

**Comment by Yomguithereal** [comment]
@Pclanglais 1 call is roughly 20 tweets. The current safe rate is about 4-5 tweets per second. Will try to increase later but we definitely won't reach 10 tweets/s.

**Comment by Yomguithereal** [comment]
30 calls per minute seem to be hitting the rate limit...

**Comment by linhui1020** [comment]
I use "tw scrape tweets" command but it returns "Failed attempt because of following exception:           
minet.twitter.exceptions.TwitterPublicAPIRateLimitError." It cannot return any tweet. Is it because of this reason? Or shall I refine my command?

**Comment by Yomguithereal** [comment]
@linhui1020 it is also possible that the cookie used by the scraper is invalid because I did not yet put in place measures to check it because we were pressed by time. Are you logged on Twitter on Firefox? Did you try tweaking `--cookie` (check out the docs).

**Comment by linhui1020** [comment]
I am sorry, I try to understand your comments. I did not use Firefox, I use Chrome and Jupyter notebook instead. I do not why  we need the cookies because I did not use it before when I scrape. I still have this issues after a month. Could you give me more information? Many thanks.

**Comment by linhui1020** [comment]
for more information, I use !minet tw scrape tweets "from:@value" > value.csv command

**Comment by Yomguithereal** [comment]
> I do not why we need the cookies because I did not use it before when I scrape.

You now need to provide a cookie to scrape because Twitter stopped allowing people from using the search function without being logged into an account. So minet now requires a cookie so it can authenticate on the website using your user account because it is the only way we can still scrape anything. Which means that 1. Twitter now knows who scrape them and 2. the rate limit has been decreased a lot (which makes scraping very slow). But since the API was cut down, there are no solutions left anyway.

> I did not use Firefox, I use Chrome and Jupyter notebook instead. 

`minet` cannot grab your auth cookie from another browser when you use Jupyter I think, so you need to provide the auth cookie directly to the command using the `--cookie` flag as explained in the command docs. If you don't know what you are doing, you need to get this cookie while visiting Twitter and checking the request headers to find the "Cookie" sent to the server from the network tab of the browser's dev console.

**Comment by linhui1020** [comment]
thanks for your time and help! I will read them and try once more.

**Comment by tloops329384** [comment]
Hi @Yomguithereal , I've noticed that scrapping is very (very) slow, but there's another problem: it seems that the scrapper goes round in circles and retrieves the same tweet several hundred times... After running for 9 hours, for example, it would have retrieved "9000" tweets, but if you analyse the data in the database and delete the duplicates, you can see that it only retrieved the last 20 tweets... Any ideas? Thank you very much for staying tuned

**Comment by Yomguithereal** [comment]
> I've noticed that scrapping is very (very) slow

yup, but there is no good way around this thanks to the rich moron who bought the website as you know :)

> After running for 9 hours, for example, it would have retrieved "9000" tweets, but if you analyse the data in the database and delete the duplicates, you can see that it only retrieved the last 20 tweets...

Good catch. I fixed this as well as some new cursor issues related to recent code changes on the public facing API. The fix is available in v1.0.0-a50.
