### ISSUE TITLE
Trouble scraping ID from youtube channel page

### ISSUE THREAD

**Issue by kat-kel** [medialab/minet#704]
It is not possible to parse nor scrape the ID of a certain YouTube channel URL with the path `/c/` (youtube.com/c/thinkerview/videos). Scraping throws a `minet.exception.InvalidURLError` even though the URL is valid and the page can be pulled up in a browser.

1. With `parse_youtube_url()` from `ural.youtube`, the ID is not being parsed from the URL.
2. With `scrape_channel_id()` from `minet.youtube.scrapers`, the exception `minet.exception.InvalidURLError` is raised when trying to get the missing ID.

The error can be reproduced like this (minet version `1.0.0a17`):
```shell
>>> import ural.youtube
>>> from minet.youtube.scrapers import scrape_channel_id

>>> url = 'youtube.com/c/thinkerview/videos'

>>> ural.youtube.parse_youtube_url(url)
YoutubeChannel(id=None, name='thinkerview')

>>> scrape_channel_id(url)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../lib/python3.11/site-packages/minet/youtube/scrapers.py", line 106, in scrape_channel_id
    response = request(channel_url, pool_manager=YOUTUBE_SCRAPER_POOL_MANAGER)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../lib/python3.11/site-packages/minet/web.py", line 1104, in request
    stack, buffered_response = atomic_resolve(
                               ^^^^^^^^^^^^^^^
  File "/.../lib/python3.11/site-packages/minet/web.py", line 634, in atomic_resolve
    buffered_response = atomic_request(
                        ^^^^^^^^^^^^^^^
  File "/.../lib/python3.11/site-packages/minet/web.py", line 516, in atomic_request
    raise InvalidURLError(url=url)
minet.exceptions.InvalidURLError
```

**Comment by boogheta** [comment]
isn't it just the missing https:// ?

**Comment by boogheta** [comment]
@Yomguithereal could it be because it's trying to access the /videos url instead of the basic channel one?
