### ISSUE TITLE
Switch to f-string for CLI templating

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/minet#71]

**Comment by Yomguithereal** [comment]
@boogheta do you think this would be an issue to drop support < 3.6 ?

**Comment by boogheta** [comment]
In my opinion the more versions supported is always the better

**Comment by Yomguithereal** [comment]
The issue is that basic templating is not that great. You cannot slice, you cannot eval expressions. Whereas the f-strings can.

**Comment by Yomguithereal** [comment]
Will find a polyfill or code one myself. Shouldn't be too hard. Then we have the beurre and the argent du beurre.

**Comment by boogheta** [comment]
that's how i like it
