### ISSUE TITLE
Youtube channels crashes if API returns a page with no result items

### ISSUE THREAD

**Issue by kat-kel** [medialab/minet#753]
The command `minet yt channels` crashes on a `Key Error` in `minet.youtube.client` if the requested YouTube channel does not have any result items on the page that the API returns. An example of this kind of response from the API is shown below:
```
{'etag': 'RuuXzTIr0OoDqI4S0RU6n4FqKEM',
 'kind': 'youtube#channelListResponse',
 'pageInfo': {'resultsPerPage': 5, 'totalResults': 0}
}
```
The valid JSON response throws a `Key Error` because it does not have the key `"items"`, as do other valid responses.
https://github.com/medialab/minet/blob/33fc1c6fb78c9c15a2aa61d0070dc941883aaa43/minet/youtube/client.py#L299

The query that produced this response was from a channel that existed (has a validated ID) but YouTube has removed the content and prevented its information from being given by the API. When you go to the URL (`https://www.youtube.com/channel/UCz1bw0-JU6pFz8WYnr9i4lw`) you see: "This account has been terminated for a violation of YouTube's Terms of Service."

**Comment by Yomguithereal** [comment]
I reopen this for later because it seems there is something else afoot here.
