### ISSUE TITLE
CrowdTangle client "post" method consistently returns the same wrong post

### ISSUE THREAD

**Issue by kat-kel** [medialab/minet#768]
When I request a deleted or private Facebook post by its `post_id` from CrowdTangle, rather than returning nothing (or the right data) the CrowdTangle API consistently returns a random post that does match the ID I requested. Unfortunately, this gives me false positives because the client ultimately received a "good" response from CrowdTangle's API, even though the data is irrelevant.

I've encountered this error even outside the Minet `CrowdTangleAPIClient` by simply opening the API URL created inside the method:
https://github.com/medialab/minet/blob/76cb84f535fb529c857a4099973a2504752d95a8/minet/crowdtangle/post.py#L12-L20

This issue can be reproduced on the following URLs:

1. https://www.facebook.com/permalink.php?story_fbid=pfbid0TP49XrZ6mMGdLNjXW9ivETD13gfaFts6hbG6NGQYRX2xcK17WAAy6zV6rRcagXTUl&amp;id=103668501476661
2. https://www.facebook.com/217438019758972/posts/584727049696732
3. https://www.facebook.com/permalink.php?story_fbid=pfbid02cKkwzzYPFTwnVfJRRQbZ6MjvtYy2K9AsNehmgnjT3VNrPPDehwXcTHVFNsrad6EXl&amp;id=451772955363043
4. https://www.facebook.com/groups/277506326438568/posts/1459416694914186/

Test results
|Facebook URL|[`minet.facebook.post_id_from_url`](https://github.com/medialab/minet/blob/76cb84f535fb529c857a4099973a2504752d95a8/minet/facebook/post_id_from_url.py)|[`post_id` returned from CrowdTangle](https://github.com/medialab/minet/blob/76cb84f535fb529c857a4099973a2504752d95a8/minet/crowdtangle/post.py#L15-L20)|
|--|--|--|
|https://www.facebook.com/permalink.php?story_fbid=pfbid0TP49XrZ6mMGdLNjXW9ivETD13gfaFts6hbG6NGQYRX2xcK17WAAy6zV6rRcagXTUl&amp;id=103668501476661|103668501476661_pfbid0TP49XrZ6mMGdLNjXW9ivETD13gfaFts6hbG6NGQYRX2xcK17WAAy6zV6rRcagXTUl|988611051326450_2317002628487279|
|https://www.facebook.com/217438019758972/posts/584727049696732|217438019758972_584727049696732|988611051326450_2317002628487279|
|https://www.facebook.com/permalink.php?story_fbid=pfbid02cKkwzzYPFTwnVfJRRQbZ6MjvtYy2K9AsNehmgnjT3VNrPPDehwXcTHVFNsrad6EXl&amp;id=451772955363043|451772955363043_pfbid02cKkwzzYPFTwnVfJRRQbZ6MjvtYy2K9AsNehmgnjT3VNrPPDehwXcTHVFNsrad6EXl|988611051326450_2317002628487279|
|https://www.facebook.com/groups/277506326438568/posts/1459416694914186/|277506326438568_1459416694914186|988611051326450_2317002628487279|

As you can see in the test results above, the same post (ID `988611051326450_2317002628487279`) is returned for all 4 different posts. In my tests, I've seen that the exact random post is sometimes different (I've also seen `2109862459044491_6678338585530166` and `2109862459044491_6677289118968446`, for example). But when requests are made to the API within a certain window of time, the API consistently returns one irrelevant post over and over again.

**Comment by Yomguithereal** [comment]
I am trying to investigate but one thing is sure, `facebook.post_id_from_url` clearly fails for link 1 & 3.

**Comment by Yomguithereal** [comment]
Apart from this I don't succeed in reproducing the issue.

**Comment by Yomguithereal** [comment]
We probably need to 1. check the returned id is consistent with the one asked because CT is not reliable and 2. Handle the parsing for link 1 & 3.

**Comment by kat-kel** [comment]
I think it's a good idea / work-around, to verify that the returned ID is consistent with the requested one.
