### ISSUE TITLE
Handle new connection error variant in serializer

### ISSUE THREAD

**Issue by Yomguithereal** [medialab/minet#770]
`newconnectionerror('<urllib3.connection.httpconnection object at 0x7f08599a5c10>: failed to establish a
new connection: [errno -5] no address associated with hostname')`

**Comment by bmaz** [comment]
newconnectionerror('<urllib3.connection.httpconnection object at 0x7fd2e35faf70>: failed to establish a new connection: [errno 101] network is unreachable')

**Comment by bmaz** [comment]
assemblee-nationale.fr/dyn/16/amendements/0917/AN/473
uvs.sn/changement-dadresse-du-site-web-institutionnel
ch-marchant.fr/web/Gerard_Marchant/12-recrutement.php
msh-lse.fr/cafe-des-donnees-2023
aps.dz/sport/153346-judo-open-africain-d-alger-treize-medailles-pour-l-algerie
u-bordeaux-montaigne.fr/fr/actualites/bibliotheques/mercredi-15-mars-perturbations-dans-les-bibliotheques-de-l-universite.html
urban-comics.com/be-urban-swamp-thing-infinite-coup-de-coeur-damir
rexecode.fr/Analyses-et-previsions/Perspectives-economiques-et-Bilan-de-l-annee/Perspectives-economiques-a-moyen-terme
ihes.fr/en/hugo-duminil-copin-in-brussels
aps.dz/economie/153029-le-president-museveni-souligne-le-role-de-l-algerie-dans-la-liberation-economique-de-l-afrique
