### ISSUE TITLE
documentation is gone

### ISSUE THREAD

**Issue by uf0** [medialab/minet#923]
the `cli.md` file on the master branch is empty

https://github.com/medialab/minet/blob/master/docs/cli.md

**Comment by boogheta** [comment]
Indeed, thanks for the report!
Until @Yomguithereal fixes it, you can read the latest version from the previous commit here: https://github.com/medialab/minet/blob/949832e231404837c87d698be81aa32dddc12d6f/docs/cli.md

**Comment by Yomguithereal** [comment]
@uf0 that's unfortunate indeed. Should be back online now.

**Comment by uf0** [comment]
thank you!
