### ISSUE TITLE
potential changes in rate limit of twitter public API

### ISSUE THREAD

**Issue by taniki** [medialab/minet#976]
I am trying to scrape tweets from a list of users with the `minet tw scrape tweets` command. It works despise X chaotic changes. I run randomly into a rate limit that is escalading quickly. I don't know if there is something to do avoid it.

![Screenshot from 2024-06-17 23-46-18](https://github.com/medialab/minet/assets/27315/d3be50f3-30a4-4100-963f-11ff3299225c)

**Comment by Yomguithereal** [comment]
Usually this happens because you are using your Twitter account on some browser or phone app while scraping, since the rate limit is shared. Could this be the issue here?

**Comment by taniki** [comment]
That's unlikely. I hit the limit last night while my browser was closed (I will double check tonight). I am also using a nitter instance to browse twitter anonymously and don't have any open tab on twitter. I am not using the app either, the limit also appears with two distinct accounts.

**Comment by Yomguithereal** [comment]
@taniki I have updated the rate limit of the scraper to be more conservative from v2.0.7. Tell me if this fixes your issue.
